vectordotdev/helm-charts

- .github/dependabot.yml
> Enable dependabot for github action updates

- .github/workflows/ci.yaml
```yaml
pr-validated:
name: pr-validated
runs-on: ubuntu-latest
needs:
- install-chart
steps:
- name: validate
run: echo "PR OK"
```
Added this from Datadog/helm-charts that can be used as a single check for PRs (otherwise each matrix job needs to be selected)
> Create a single check that can be used for PRs

- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/README.md.gotmpl
- charts/vector/ci/default-agent-values-BROKEN.yaml
- charts/vector/ci/default-agent-values.yaml
- charts/vector/templates/_pod.tpl
- charts/vector/templates/haproxy/deployment.yaml
- charts/vector/templates/haproxy/service.yaml
- charts/vector/templates/secret.yaml
- charts/vector/values.yaml
> chore: vector 0.1.0-alpha.1

- charts/vector/README.md
- charts/vector/templates/_pod.tpl
- charts/vector/values.yaml
> feat(vector): Add override for default Vector command

- charts/vector/README.md
- charts/vector/templates/haproxy/service.yaml
- charts/vector/templates/service-headless.yaml
- charts/vector/templates/service.yaml
- charts/vector/values.yaml
> feat(vector): Add support for topologyKeys on all Services

- charts/vector/templates/_helpers.tpl
> fix(vector): Create ports for api from customConfig

- charts/vector/README.md
- charts/vector/ci/aggregator-ingress-values.yaml
- charts/vector/templates/ingress.yaml
- charts/vector/values.yaml
> feat(vector): Add optional Ingress resource

- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/templates/pdb.yaml
- charts/vector/values.yaml
> feat(vector): Add optional PodDisruptionBudget resource for Vector

- .github/cliff.toml
- CHANGELOG.md
> chore: Fix cliff config tag pattern

- charts/vector/README.md
- charts/vector/values.yaml
These were used in templates but not documented nor included in the values file.
> chore: Document nameOverride and fullnameOverride

- charts/vector/README.md
- charts/vector/templates/psp.yaml
- charts/vector/templates/rbac.yaml
- charts/vector/values.yaml
> feat(vector): Allow option PSP to be created for Agent role

- charts/vector/README.md
- charts/vector/ci/manual-port-values.yaml
- charts/vector/templates/_pod.tpl
- charts/vector/templates/service-headless.yaml
- charts/vector/templates/service.yaml
- charts/vector/values.yaml
> feat(vector): Allow for manually setting ports for container and services

- charts/vector/templates/daemonset.yaml
- charts/vector/templates/deployment.yaml
- charts/vector/templates/statefulset.yaml
> feat(vector): Create checksum annotations for existingConfig and extraConfigs

- charts/vector/README.md
- charts/vector/templates/_pod.tpl
- charts/vector/templates/daemonset.yaml
- charts/vector/templates/deployment.yaml
- charts/vector/templates/haproxy/deployment.yaml
- charts/vector/templates/statefulset.yaml
- charts/vector/values.yaml
BREAKING CHANGE: Renamed existingConfig to existingConfigMaps, renamed
haproxy.existingConfig to haproxy.existingConfigMaps removed extraConfigs
Closes #66
> feat(vector)!: Consolidate existing/extraConfig options

- charts/vector/README.md
- charts/vector/templates/_helpers.tpl
- charts/vector/values.yaml
This paramter wasn't ported from the old charts, I noticed it while writing the upgrade guides
> feat(vector): Add parameter to include additional labels on all resources

- charts/vector/README.md
- charts/vector/ci/extra-volume-values.yaml
- charts/vector/templates/_pod.tpl
- charts/vector/values.yaml
> feat(vector): Add extraVolumes and extraVolumeMounts parameters

- charts/vector/ci/dupe-ports-values.yaml
> chore(vector): Fix helm lint

- CHANGELOG.md
> chore: Ready 0.1.0-alpha.4 vector release

- charts/vector/README.md
- charts/vector/ci/initContainers-values.yaml
- charts/vector/templates/_pod.tpl
- charts/vector/values.yaml
Closes #78
Internally requested
> feat(vector): Add support for user defined initContainers for Vector Pods

- charts/vector/README.md
> chore(vector): Update readme badge

- charts/vector/templates/haproxy/configmap.yaml
Closes #88
Ref: https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector-aggregator/templates/haproxy/_helpers.tpl#L49-L58
> fix(vector): Fix vector proto in haproxy config

- CHANGELOG.md
> chore: Prep changelog for release

- charts/vector/README.md
- charts/vector/values.yaml
Closes #103
I needed to add a type hint to the comment so the readme table has the right type
> fix(vector): Fix type for podDisruptionBudget.maxUnavailable

- charts/vector/README.md
- charts/vector/values.yaml
> docs(vector): Add example customConfig in values.yaml

- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/README.md.gotmpl
- charts/vector/docs/Migrate_from_vector-agent.md
- charts/vector/docs/Migrate_from_vector-aggregator.md
> docs(vector): Add upgrade docs

- CHANGELOG.md
- charts/vector/Chart.yaml
> chore(vector): Prepare 0.1.0 release for vector chart

- CHANGELOG.md
> chore(vector): Generate changelog for 0.1.1

- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/templates/podmonitor.yaml
- charts/vector/values.yaml
Add back the ability to specify additional labels on PodMonitor. Fixes #110
> feat(vector): Add back additionalLabels

- charts/vector-agent/Chart.yaml
- charts/vector-aggregator/Chart.yaml
- charts/vector/Chart.yaml
- charts/vector/README.md
Signed-off-by: bradybot <bradybot@timber.io>
> feat(vector): Upgrade Vector to 0.18.0

- CHANGELOG.md
> fix(vector): Generate Vector 0.2.1 CHANGELOG

- CHANGELOG.md
> chore: Update changelog for 0.18.1 update

- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/ci/vector-templating-values.yaml
> docs(vector): Fix example and CI for Vector templating

- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/values.yaml
> docs(vector): Clarify usage of secrets.generic and env

- charts/vector-agent/Chart.yaml
- charts/vector-aggregator/Chart.yaml
- charts/vector/Chart.yaml
- charts/vector/README.md
> feat(vector): Update charts to Vector 0.19.0

- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/values.yaml
> docs(vector): Fix comment on autoscaling option

- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/templates/rbac.yaml
> fix(vector): Include common labels on ClusterRole resource

- .github/release-changelog.sh
- .github/release-vector-version.sh
- README.md
- chore: Add scripts to prepare a new changelog and update the Vector image
- chore: Add notes for new release scripts
Closes vectordotdev/vector#10656
> chore: Script and document release process

- .github/workflows/ci.yaml
Matches https://github.com/vectordotdev/vector/pull/11118
> chore: Update supported k8s versions

- .github/workflows/ci.yaml
- charts/vector-agent/Chart.yaml
- charts/vector-aggregator/Chart.yaml
Since we weren't able to get this working and it seems to be something
specific to `kind` rather than anything with the chart.
> chore: comment out CI test of 1.22

- .github/workflows/ci.yaml
- charts/vector-agent/Chart.yaml
- charts/vector-aggregator/Chart.yaml
- charts/vector/Chart.yaml
- charts/vector/README.md
> feat(vector): Upgrade Vector to 0.19.1

- charts/vector-agent/Chart.yaml
- charts/vector-aggregator/Chart.yaml
- charts/vector-shared/Chart.yaml
- charts/vector/Chart.yaml
- charts/vector/README.md
> chore: Fix maintainer email

- CHANGELOG.md
> chore: Fix changelog for maintainer email change

- charts/vector-agent/Chart.yaml
- charts/vector-aggregator/Chart.yaml
- charts/vector/Chart.yaml
- charts/vector/README.md
> fix: Bump Vector versions to v0.19.3

- charts/vector/Chart.yaml
- charts/vector/README.md
> feat: Update to use 0.20.0

- .github/cliff.toml
- .github/release-changelog.sh
- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/templates/rbac.yaml
> feat(vector): Add list verb for upcoming kube-rs change

- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/values.yaml
> docs(vector): Update comment for autoscaling.enabled

- .github/workflows/ci.yaml
- charts/vector/Chart.yaml
- charts/vector/README.md
> chore: Always run CI as to not block PRs

- charts/vector/templates/_pod.tpl
- charts/vector/templates/configmap.yaml
- charts/vector/templates/haproxy/configmap.yaml
- charts/vector/templates/haproxy/deployment.yaml
- charts/vector/templates/haproxy/service.yaml
- charts/vector/templates/service-headless.yaml
- charts/vector/templates/service.yaml
- fix(vector)!: fix conditionals for haproxy.existingConfigMap
- fix(vector)!: fix conditionals for existingConfigMaps
Closes #181
> fix(vector)!: fix conditionals for existingConfigMaps and haproxy.existingConfigMap

- charts/vector/templates/haproxy/_helpers.tpl
> fix(vector)!: use haproxy.image.tag as its version label value

- CHANGELOG.md
> chore(vector): update changelog for 0.7.0

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
> fix(vector): Bump Vector to v0.20.1

- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/templates/_helpers.tpl
- charts/vector/templates/_pod.tpl
- charts/vector/templates/pdb.yaml
> feat(vector): Switch policy version based on capabilities and k8s version

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
- feat(vector): Bump image to 0.21.0
- chore: update changelog
> feat(vector): Bump image to 0.21.0

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
- feat(vector): Bump image to 0.21.1
- chore: changelog
> fix(vector): Bump image to 0.21.1

- charts/vector/Chart.yaml
- charts/vector/README.md
> fix: Bump to Vector 0.21.2

- .github/helm-docs.sh
- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/values.yaml
Fixes #217 
See the linked issue for more details
> chore(deps): Update haproxy-alpine to 2.4.17

- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/templates/daemonset.yaml
- charts/vector/values.yaml
/fix https://github.com/vectordotdev/helm-charts/issues/6
> feat(vector): Allow enabling of collection vector container logs by vector

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
Signed-off-by: Jesse Szwedko <vector@datadoghq.com>
> feat(vector): Bump Vector to 0.23.0

- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/templates/_helpers.tpl
- charts/vector/templates/haproxy/_helpers.tpl
- charts/vector/templates/haproxy/hpa.yaml
- charts/vector/templates/hpa.yaml
Signed-off-by: Tuan Anh Nguyen <tuananh.nguyen-ext@commercetools.de>
Fixes https://github.com/vectordotdev/helm-charts/issues/186
> Add support for autoscaling v2

- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/templates/hpa.yaml
- charts/vector/values.yaml
Hi, this PR add behavior setting to hpa.
Signed-off-by: tombokombo <tombo@sysart.tech>
> Add hpa behavior

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
Adding to 0.15.0 release since that wasn't released yet.
> fix(vector): Bump to Vector v0.23.3

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
Accidentally merged in develop to master without the commit bumping the
Vector version.
> fix(vector): Actually release version bump

- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/ci/extraContainers-values.yaml
- charts/vector/ci/haproxy-extraContainers-values.yaml
- charts/vector/templates/_pod.tpl
- charts/vector/templates/haproxy/deployment.yaml
- charts/vector/values.yaml
extraContainers allows you to run sidecars containers along with the main container
Closes #224
> added extraContainers option for vector & haproxy pods

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/templates/_pod.tpl
- charts/vector/values.yaml
> feat(vector): Add support for setting the pod hostNetwork (#213)

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/ci/aggregator-all-values.yaml
- charts/vector/ci/vector-templating-values.yaml
> feat(vector): Bump to Vector 0.24.0

- charts/vector/README.md
- charts/vector/examples/datadog-values.yaml
- charts/vector/templates/_pod.tpl
- charts/vector/values.yaml
> feat(vector): :sparkles: add envFrom support

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
- updated changelog
- updated chart image
> feat(vector): :sparkles: Release 2022-10-04

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/templates/_pod.tpl
> fix(vector): :bug: pod tpl

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/README.md.gotmpl
- charts/vector/docs/Migrate_from_vector-agent.md
- charts/vector/docs/Migrate_from_vector-aggregator.md
- charts/vector/docs/quickstart.md
> fix(vector): Apply various suggested changes from JetBrains markdown and proofreading inspections

- charts/vector/Chart.yaml
- charts/vector/README.md
> feat(vector): Update Vector image to 0.24.2

- charts/vector/README.md
- charts/vector/values.yaml
> feat(vector): Refresh chart documentation and comments

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/ci/vector-templating-values.yaml
- feat(vector): Update Vector image to 0.25.1
- chore: update changelog
Prepped for chart release
> feat(vector): Update Vector image to 0.25.1

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
> fix(vector): Update to Vector 0.25.2

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/ci/vector-templating-values.yaml
> feat(vector): Upgrade chart to Vector 0.26.0

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
> feat(vector): Bump to v0.27.0 release of Vector

- charts/vector/values.yaml
Forgot to add "balancer".
Co-authored-by: marcleibold <leibold485@gmail.com>
> Fix comment.

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
> fix(vector): Bump Vector to 0.27.1

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
> feat(vector): Bump Vector version to 0.28.0

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
- fix(vector): Bump Vector to 0.28.1
- Regenerate docs
> jszwedko/bump vector 0.28.1

- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/templates/podmonitor.yaml
- charts/vector/values.yaml
Very simple fix, the template for vector podMonitor didn't have any interval configuration
> fix(vector): vector PodMonitor interval configuration

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
- feat(vector): Bump Vector to 0.29.0
- Regenerate CHANGELOG and README
> feat(vector): Bump Vector to 0.29.0

- README.md
improve Releasing documentation
> Update README.md with Releasing documentation improvements

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
> feat(vector): Bump Vector version to 0.30.0

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
> feat(vector): Bump Vector image to 0.31.0

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
> fix(vector): Bump Vector to 0.32.1

- charts/vector/templates/extra-manifests.yaml
- charts/vector/values.yaml
Hi. This will allow users to create resources for vector such as dashboards for grafana
> Ability to add extraObjects

- charts/vector/README.md
> extraObjects fix lint

- .github/workflows/ci.yaml
> chore(vector): Add lint-docs to CI check

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
> fix(vector): Bump Vector version to v0.32.2

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
> feat(vector): Bump Vector version to v0.33.0

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
> feat(vector): Bump charts to Vector v0.33.1

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
> feat(vector): Bump to Vector v0.34.0

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
> fix(vector): Bump Vector to 0.34.1

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
> feat(vector): Bump to Vector v0.34.2

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
> feat(vector): Bump Vector to v0.35.0

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/templates/_pod.tpl
Should apply regardless of whether deployed as an "Agent" or
"Aggregator".
Fixes: #359
> fix(vector): Apply `logLevel` config option

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
> fix(vector): Bump to Vector v0.35.1

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
> feat(vector): Bump Vector version to v0.36.0

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
> feat(vector): Bump Vector to v0.37.0

- charts/vector/Chart.yaml
- charts/vector/templates/configmap.yaml
- charts/vector/templates/daemonset.yaml
- charts/vector/templates/deployment.yaml
- charts/vector/templates/ingress.yaml
- charts/vector/templates/secret.yaml
- charts/vector/templates/service-headless.yaml
- charts/vector/templates/service.yaml
- charts/vector/templates/serviceaccount.yaml
- charts/vector/templates/statefulset.yaml
Reverts vectordotdev/helm-charts#394
> fix(vector): Revert add `namespace` to manifests"

- charts/vector/templates/_pod.tpl
- charts/vector/values.yaml
fix of https://github.com/vectordotdev/helm-charts/issues/391
> fix(vector): add hostAliases in pod spec

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
> fix(vector): Bump to Vector v0.40.1

- charts/vector/README.md
- charts/vector/values.yaml
> chore(vector): Lint values.yaml

- CHANGELOG.md
> chore(vector): Prepare v0.35.3 release

- CHANGELOG.md
> chore(vector): Prepare v0.36.0 release

- charts/vector/Chart.yaml
- charts/vector/README.md
> fix(vector): Bump Vector to v0.41.1

- CHANGELOG.md
> chore(vector): Prepare v0.36.1 chart release

- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/README.md.gotmpl
There is no `--name` flag anymore and other flags should be at the end.
> chore(vector): Update README for Vector chart for Helm 3

- CHANGELOG.md
Figured we could release the last couple of changes.
> chore(vector): Prepare v0.39.0 release

- charts/vector/Chart.yaml
- charts/vector/README.md
Ref: https://github.com/vectordotdev/vector/issues/22152
> feat(vector): Bump Vector to v0.44.0

- CHANGELOG.md
Ref: https://github.com/vectordotdev/vector/issues/22152
> feat(vector): Regenerate CHANGELOG for vector-0.40.0

- release.sh
To be tested with the next release.
> feat(releasing): introduce release script

- charts/vector/Chart.yaml
- charts/vector/README.md
Ref: https://github.com/vectordotdev/vector/issues/22445
> chore(releasing): Update Vector version to 0.45.0

- release.sh
Based on the learning from the latest release.
> chore(releasing): fix release.sh versions and step order

- charts/vector/Chart.yaml
- charts/vector/README.md
- charts/vector/templates/configmap.yaml
- charts/vector/templates/daemonset.yaml
- charts/vector/templates/deployment.yaml
- charts/vector/templates/ingress.yaml
- charts/vector/templates/podmonitor.yaml
- charts/vector/templates/rbac.yaml
- charts/vector/templates/secret.yaml
- charts/vector/templates/service-headless.yaml
- charts/vector/templates/service.yaml
- charts/vector/templates/serviceaccount.yaml
- charts/vector/templates/statefulset.yaml
This prevents errors when namespaces are "numeric"
> fix(vector): Quote namespace strings

- charts/vector/Chart.yaml
- charts/vector/README.md
Ref: https://github.com/vectordotdev/vector/issues/22784
> feat(vector): Update Vector version to 0.46.0

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
Ref: https://github.com/vectordotdev/vector/issues/22784
> chore(releasing): Regenerate CHANGELOG for 0.42.0

- charts/vector/Chart.yaml
- charts/vector/README.md
Ref: https://github.com/vectordotdev/vector/issues/22858
> feat(releasing): Update Vector version to 0.46.1 and Helm docs

- CHANGELOG.md
https://github.com/vectordotdev/vector/issues/22858
> chore(releasing): write changelog for 0.42.1

- charts/vector/Chart.yaml
- charts/vector/README.md
Ref: https://github.com/vectordotdev/vector/issues/23037
> feat(releasing): Update Vector version to 0.47.0 and Helm docs

- CHANGELOG.md
- release.sh
Ref: https://github.com/vectordotdev/vector/issues/23037
> chore(vector): Regenerate CHANGELOG for 0.43.0

- charts/vector/Chart.yaml
- charts/vector/README.md
Ref: https://github.com/vectordotdev/vector/issues/23257
> feat(releasing): Update Vector version to 0.48.0 and Helm docs

- CHANGELOG.md
- charts/vector/Chart.yaml
- charts/vector/README.md
Ref: https://github.com/vectordotdev/vector/issues/23257
> chore(vector): Regenerate CHANGELOG for 0.44.0

- charts/vector/Chart.yaml
- charts/vector/README.md
Ref: https://github.com/vectordotdev/vector/issues/23525
> feat(releasing): Update Vector version to 0.49.0 and Helm docs

- charts/vector/Chart.yaml
- charts/vector/README.md
- release.sh
> chore(releasing): Bump chart version to 0.46.0
