charts/vector/Chart.yaml, charts/vector/README.md, charts/vector/templates/NOTES.txt, charts/vector/templates/_pod.tpl, charts/vector/templates/daemonset.yaml, charts/vector/templates/deployment.yaml, charts/vector/templates/haproxy/deployment.yaml, charts/vector/templates/haproxy/serviceaccount.yaml, charts/vector/templates/service-headless.yaml, charts/vector/templates/service.yaml, charts/vector/templates/serviceaccount.yaml, charts/vector/templates/statefulset.yaml, charts/vector/values.yaml
- fix: Add -0 to kubeVersion to fix comparison on EKS
- fix: Render env in pod template
- chore: Document podAnnotation option
- chore: Improve NOTES output accuracy
- feat: Document and implement serviceaccount options
- feat: Add checksum of generated configmap for all roles
- feat: Add podLabels for all workloads
- feat: Add priorityClassName for all workloads
- chore: Minor comments rewrites
- feat: Add pullSecrets to pod template
- feat: Set Vector args through values file
- feat: Allow for manual overriding of Service ports
- chore: Update docs
=> spencer/vector alpha.2

.github/semantic.yml, README.md
Closes #39
As part of this, we also will be making the `develop` branch the **default** for the repo and only release charts when `develop` is merged into `master`
=> feat: Add config for semantic PRs app

charts/vector/Chart.yaml, charts/vector/README.md, charts/vector/ci/haproxy-values.yaml, charts/vector/templates/haproxy/deployment.yaml
Resolves the following issue:
```shell
Error: UPGRADE FAILED: template: vector/templates/haproxy/deployment.yaml:19:28: executing "vector/templates/haproxy/deployment.yaml" at <include (print $.Template.BasePath "haproxy/configmap.yaml") .>: error calling include: template: no template "vector/templateshaproxy/configmap.yaml" associated with template "gotpl"
```
=> fix: Add missing `/` to haproxy configmap path

README.md
These charts used to be hosted within the main repo, and #24 added a combined chart that looks to be the future. This adds a (likely short-term) pointer in the README to help guide folks to the right path.
Maybe most importantly, please consider this a strawman since I'm not entirely certain this is the chart y'all recommend folks use!
This is related to https://github.com/vectordotdev/vector/pull/9396
=> docs(vector): Clarify suggested usage

charts/vector/ci/dupe-ports-values.yaml, charts/vector/templates/_helpers.tpl
=> fix(vector): Fix ordering of `default` function in port helpers

charts/vector/Chart.yaml, charts/vector/README.md, charts/vector/templates/secret.yaml, charts/vector/values.yaml
Closes #72
This change aligns us with [Datadog's chart](https://github.com/DataDog/helm-charts/blob/main/charts/datadog/templates/secret-api-key.yaml#L11)
=> feat(vector)!: Update secrets.generic to take unencoded values

charts/vector/README.md, charts/vector/templates/service-headless.yaml, charts/vector/templates/service.yaml
Closes #100
This mirrors the condition used for both the service and service-headless.
Headless services are generally more useful for load balancing or being able
to select specific instances from a StatefulSet, but rather than introducing
more configuration this seems simpler unless a user requests more specific options.
=> fix(vector): Toggle both service and headless service with service.enabled

charts/vector/Chart.yaml, charts/vector/README.md, charts/vector/README.md.gotmpl
Closes #106
Fun issue - similar to why it breaks when templated through Helm, helm-docs templating is also processing go template functions here. I resolved by just doing the same thing _again_, instructing the template engine to print the entire string.
=> docs(vector): Handle helm-docs processing of vector template example

CHANGELOG.md
Release chart with `0.18.0` image and re-add additionalLabels to PodMonitor resource.
=> chore(vector): Generate changelog for 0.2.0

charts/vector/templates/_pod.tpl, charts/vector/templates/hpa.yaml
fix two typo:
* Use `podPriorityClassName` in values just like before in `_pod.tpl`
* Not `Statefulset`, is `StatefulSet` in hpa.yml (it also cause some error).
```
Events:
Type     Reason          Age                   From                       Message
----     ------          ----                  ----                       -------
Warning  FailedGetScale  2m5s (x275 over 72m)  horizontal-pod-autoscaler  no matches for kind "Statefulset" in group "apps"
```
=> fix(vector): typo `podPriorityClassName` & `StatefulSet`

charts/vector/Chart.yaml, charts/vector/README.md, charts/vector/templates/hpa.yaml
What this PR does / why we need it:
Reorders the list in spec.metrics for all components' HPAs in order to circumvent issue kubernetes/kubernetes#74099. Without this change, GitOps style CD tools such as Argo will consider the HPAs permanently out of sync due to the following discrepancy:
Fixes #118
=> fix(vector): Switch metric list order in HPA

charts/vector-aggregator/Chart.yaml, charts/vector-aggregator/templates/haproxy/deployment.yaml, charts/vector-aggregator/templates/haproxy/serviceaccount.yaml
This PR fix the 'if' condition in the serviceaccount.yaml file for use only the value in haproxy block in the value file (haproxy.serviceAccount.create).
And add a condition 'if' in the deployment of haproxy for add or remove the annotation 'serviceAccount' if the value is 'haproxy.serviceAccount.create' is true or false.
If I understood correctly, the SA is only used for the PSP and it is deprecated from version v1.21.
=> fix(vector-aggregator): Fix the conditions for enable/disable SA on the HAProxy

README.md, charts/vector-agent/Chart.yaml, charts/vector-aggregator/Chart.yaml, charts/vector-shared/Chart.yaml
=> chore: Deprecate old Vector Agent/Aggregator/Shared charts

charts/vector/Chart.yaml, charts/vector/README.md, charts/vector/templates/podmonitor.yaml, charts/vector/values.yaml
Add ability to set honorLabels and honorTimestamps for the PodMonitor which can be deployed with the vector helm chart. Fixes #152
=> feat(vector): Add honorLabels and honorTimestamps to PodMonitor

charts/vector/README.md, charts/vector/README.md.gotmpl
Hi
The current example generates Loki labels ending with a newline. This fixes it
=> docs(vector): Fix loki label ends with new line

.github/workflows/ci.yaml, .github/workflows/release.yaml, CHANGELOG.md, charts/vector/Chart.yaml, charts/vector/README.md, charts/vector/docs/quickstart.md, charts/vector/examples/datadog-values.yaml, charts/vector/templates/NOTES.txt, charts/vector/templates/_helpers.tpl
- feat(vector): Improve help text printed by NOTES.txt and reduce duplication of internal templates (#189)
- chore(deps): bump helm/chart-releaser-action from 1.3.0 to 1.4.0 (#190)
- docs(vector): Add quickstart values and docs (#176)
- feat(vector): Add help output for configurations with datadog_agent source (#178)
- fix(vector): Bump Vector to v0.20.1 (#195)
=> chore: release version 0.9.0

CHANGELOG.md, charts/vector/Chart.yaml, charts/vector/README.md, charts/vector/templates/rbac.yaml
The ability to list and watch nodes will be required to annotate logs from `kubernetes_logs` sources in the future. 
See https://github.com/vectordotdev/vector/pull/12730 for more details.
=> feat(vector): add RBAC to list and watch nodes

CHANGELOG.md, charts/vector/Chart.yaml, charts/vector/README.md, charts/vector/templates/_pod.tpl, charts/vector/values.yaml
Signed-off-by: Tomer Epstein <tomer.epstein@sap.com>
**Motivation**
add better integrity to the image version, we should provide a way to add a digest option to the chart images this way we can validate the image version
**Approach**
How does this change address the problem?
Add digest option to vector chart,
By adding a new sha field to the pod file and concatenate it to the image string address when provided.
**Pull Request status**
=> feat(vector): Add digest option to vector image

CHANGELOG.md, charts/vector/Chart.yaml, charts/vector/README.md, charts/vector/templates/_pod.tpl, charts/vector/values.yaml
Hi, there are missing optional lifecycle hooks, so this PR reintroduce them, as they are in deprecated vector-agent chart.
=> feat(vector): Add lifecycle hooks

charts/vector/ci/extraContainers-and-extraVolumeMounts-values.yaml, charts/vector/templates/_pod.tpl
`extraVolumeMounts` should be located before `extraContainers`
otherwise, if extraContainers is not null, yaml is not valid and extraVolumeMounts is impossible to use.
=> fix: extraVolumeMounts

.github/workflows/release.yaml
We're not longer publishing `vector-agent` or `vector-aggregator`, and ignoring them during linting as well. This should stop the release process from trying to publish them as well.
```shell
Looking up latest tag...
Discovering changed charts since 'vector-0.16.0'...
Installing chart-releaser on /opt/hostedtoolcache/cr/v1.4.1/x86_64...
Adding cr directory to PATH...
Packaging chart 'charts/vector-agent'...
Successfully packaged chart in /home/runner/work/helm-charts/helm-charts/charts/vector-agent and saved it to: .cr-release-packages/vector-agent-0.21.3.tgz
Packaging chart 'charts/vector-aggregator'...
Successfully packaged chart in /home/runner/work/helm-charts/helm-charts/charts/vector-aggregator and saved it to: …
```
=> fix(ci): Skip release if it already exists

charts/vector/Chart.yaml, charts/vector/README.md, charts/vector/templates/NOTES.txt, charts/vector/templates/_helpers.tpl
Fixes #254 by removing the escape codes completely, as there isn't a native way to detect support during templating. It was fun while it lasted, but ultimately not great for Windows users.
Below is the NOTES output from an example install.
```text
NOTES:
--------------------------------------------------------------------------------
__   __  __
\ \ / / / /
\ V / / /
\_/  \/
V E C T O R
--------------------------------------------------------------------------------
Vector is starting in your cluster. After a few minutes, you can use Vector's
API to view internal metrics by running:
$ kubectl -n default exec -it statefulset/vector -- vector top
-------------------------------------------------------------------------------- …
```
=> fix(vector): Remove color codes in NOTES.txt

charts/vector/templates/haproxy/deployment.yaml
Very simple fix, the template for haproxy deployment seems to use the old naming for imagePullSecrets
Thanks in advance! :smile_cat:
=> fix(vector): Update haproxy to use image.pullSecrets

charts/vector/templates/_helpers.tpl, charts/vector/templates/haproxy/_helpers.tpl
ArgoCD uses `helm template` which fails to get the right api-version on k8s-version 1.21
On 1.21 cluster - the helm chart will fail!
As described [here](https://github.com/argoproj/argo-cd/issues/7291), the solution is to use `.Capabilities.APIVersions.Has` over `api/version/kind` instead of over just `api/version`
Enable autoscaling on values.yml and run
```bash
helm template . --kube-version 1.21
```
Before fix the hpa would get `v2` (which does not exist on 1.21), after fix it will get `v2beta2` 
Run
```bash
helm template . --kube-version 1.24
```
Before and after fix you'll get `v2`
=> fix HorizontalPodAutoscaler helm template api version

charts/vector/Chart.yaml, charts/vector/README.md, charts/vector/ci/aggregator-all-values.yaml, charts/vector/templates/daemonset.yaml, charts/vector/templates/deployment.yaml, charts/vector/templates/statefulset.yaml, charts/vector/values.yaml
Would it be alright to add annotations for the pod controller of Vector? 
My specific use-case is that ArgoCD deployment doesn't work with the rollWorkload option, so I would like to be able to put the stakater/reloader annotation on the deployment to roll Vector when its ConfigMap dependencies are updated.
=> feat(vector): add annotations for deployment, daemonset, statefulset

charts/vector/Chart.yaml, charts/vector/README.md, charts/vector/templates/daemonset.yaml, charts/vector/values.yaml
add [minReadySeconds](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/daemon-set-v1/#DaemonSetSpec:~:text=minReadySeconds%20(int32)). useful when we have a lot of nodes and we wanted to be sure the pod is fully deployed, otherwise may want to reschedule this job and investigate.
=> feat(vector): add minReadySeconds for daemonsets

charts/vector/templates/statefulset.yaml
Do not include storageClassName attribute if not provided (default). Currently the persistence.storageClassName value is not provided by default, which results in an empty string storageClassName attribute in the StatefulSet template. This inadvertently disables dynamic PV provisioning.
If no persistence.storageClassName value is provided, then the attribute should not be present in the rendered StatefulSet, allowing the PVC to use the cluster's default storage class.
=> Fix default/missing storageClassName

charts/vector/Chart.yaml, charts/vector/README.md, charts/vector/templates/daemonset.yaml
In this case, we must use the global (root) context for access to `.Values.minReadySeconds` variable.
Without it, Helm try to find it in `.Values.updateStrategy` scope.
closes: #306
=> fix(vector): move minReadySeconds to global scope

charts/vector/Chart.yaml, charts/vector/README.md, charts/vector/templates/_pod.tpl, charts/vector/values.yaml
Signed-off-by: Ugur Can Ozturk [ugurozturk918@gmail.com](mailto:ugurozturk918@gmail.com)
/kind feature
* Using hostPath as a data directory might not be best practice unless it has to be; I believe users who would like to use emptyDir instead of hostPath should be able to do that.
* It would be great if mounted volumeMounts can be overridden by users based on the logs data path that they want to collect.
* Another good feature would be changing log level easily
As an alternative log collector we're trying to use vector hoping it is more lightweight and performative. But since it's trying to write mounted hostpath for the data-dir; and since as a cluster-wide policy we don't allow any write actions for the hostpath volumes; it could not run with current helm chart values. I'm hoping this …
=> feat(vector): volumes/volumeMounts, logLevel and dataDir

charts/vector/Chart.yaml, charts/vector/README.md, charts/vector/templates/podmonitor.yaml, charts/vector/values.yaml
Motivation:
- add the ability to pass specified labels from the vector's pod to metrics
Solution: 
Add podTargetLabels to PodMonitor Spec.
More info:
https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.PodMonitorSpec
=> feat(vector): add podMonitor.podTargetLabels

charts/vector/README.md, charts/vector/templates/_pod.tpl, charts/vector/values.yaml
This adds the ability to set the `pod.spec.shareProcessNamespace` value in the pod template (defaults to `false`), which allows the sidecars container to be able to send the reload signal (`SIGHUP`) to the vector process.
=> feat: support shareProcessNamespace is pod.spec

charts/vector/README.md, charts/vector/templates/hpa.yaml, charts/vector/values.yaml
Allowing to add annotations to the Vector's HPA, this is needed when someone want to use [kube-metrics-adapter](https://github.com/zalando-incubator/kube-metrics-adapter/blob/e54f3b88cf5e60e02c8523b4b806dfd5dfe00f28/README.md)
=> Add annotations to Vector's HPA

charts/vector/README.md, charts/vector/templates/deployment.yaml, charts/vector/templates/statefulset.yaml, charts/vector/values.yaml
The chart currently supports `minReadySeconds` for DaemonSet-based deployments of the Vector agent. This PR extends this value to also apply to StatefulSets and Deployment specs.
=> fix(vector): add minReadySeconds to StatefulSet and Deployment specs

.github/kubeval.sh, .github/workflows/ci.yaml
Without this PRs that don't make changes to any charts don't pass CI.
I think the overhead of just testing all charts is fairly minimal.
=> chore(vector): Run CI on any changes

.github/kubeval.sh
This allows the template to render the correct manifest for the
kubernetes version under test.
=> chore(vector): Specify the kube version when templating in CI

CHANGELOG.md, charts/vector/Chart.yaml, charts/vector/README.md
=> fix(vector): Bump Vector version to v0.36.1

charts/vector/Chart.yaml, charts/vector/README.md, charts/vector/templates/deployment.yaml, charts/vector/templates/haproxy/deployment.yaml, charts/vector/templates/statefulset.yaml, charts/vector/values.yaml
When using any autoscaler, replicas should not be set on any Deployment or StatefulSet. This helm chart has hooks for defining an HPA, but there are times when users may want to create their own, or use something external like [KEDA](https://keda.sh). In our case, we want to use KEDA for scaling based on kafka lag and other triggers. This largely works as expected, but I need to prevent the `replicas` field from being populated, or else things appear out-of-sync when the external autoscaler is doing its thing (we use ArgoCD and it will show the project as out-of-sync because of replicas).
The feature here is just to offer an additional field under `autoscaling` options: `external: true/false`.
=> enhancement(vector): Allow external autoscaler

charts/vector/Chart.yaml, charts/vector/README.md, charts/vector/templates/_helpers.tpl, charts/vector/templates/_pod.tpl, charts/vector/values.yaml
This fixes #237 by allowing the user of the chart to set a static `.Values.image.base` field.
When this is set, it will be used to replace the `base` that is used in the `AppVersion` where appropriate, so that users can upgrade their chart without having to constantly change the image tag to keep the version up.
The order of precedence for this is:
1. `.Values.image.tag` overrides everything
2. `.Values.image.base` overrides the base of the `.Chart.AppVersion`
3. `.Chart.AppVersion` is the default
I could not for the life of me get chart testing to work locally for some reason, but I am happy to update the README.md by hand if necessary.
=> enhancement(vector): Update the image fields to allow for a static base name

charts/vector/templates/haproxy/deployment.yaml
Hello friends!
I just encountered a small issue with the `vector` chart when trying to add an optional init-container for the HAProxy deployment. The line that expands `.Values.haproxy.initContainers` doesn't trim the initial whitespaces, causing the first line of the rendered YAML to have 16 spaces instead of the desired 8. 
Added a `{{-` to trim the initial whitespaces (and newline), and used `nindent` to add the newline again. This aligns with other expansions within this template :) 
This is my first PR, so please let me know if you need any additional info or if I need to change the commit message etc. Tried to keep it similar to the existing ones ;)  
Cheers!
=> fix(vector): Fix indentation for haproxy.initContainers

charts/vector/Chart.yaml, charts/vector/templates/configmap.yaml, charts/vector/templates/daemonset.yaml, charts/vector/templates/deployment.yaml, charts/vector/templates/ingress.yaml, charts/vector/templates/secret.yaml, charts/vector/templates/service-headless.yaml, charts/vector/templates/service.yaml, charts/vector/templates/serviceaccount.yaml, charts/vector/templates/statefulset.yaml
To prevent argo CD InvalidSpecError
=> fix(vector): Add `namespace` to manifests

CHANGELOG.md, charts/vector/Chart.yaml, charts/vector/README.md, charts/vector/templates/statefulset.yaml, charts/vector/values.yaml
Hello! 👋 
This PR adds a new variable in the `values.yaml` file: `persistence.retentionPolicy`. 
This allow users to define which is the PVC retention policy for the created Statefulsets. Kubernetes by default sets a `Remain` policy, meaning that no PVC are removed when the Statefulset is down-scaled or removed.  With this new setting, users can tell Kubernetes to remove these disks, for example for non production environment. 
This variable has a default set to `{}`, meaning that this setting will not be applied and Kubernetes will apply its default value, so current statefulsets will not be affected.
More info about this new feature here:
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention
I've run the following commands to ensure that …
=> enhancement(vector): Add `persistence.retentionPolicy` for configuring Statefulset PVC retention policy

.github/workflows/release.yaml
Needed to publish to ghcr.io. Will follow up to see the limited set of permissions required.
=> chore(vector): Remove `permissions` and use default permissive permissions

charts/vector/templates/daemonset.yaml
This prevents from settings empty annotations like `annotations: {}` which causes argocd to always see DaemonSet as out of sync, because a DaemonSet will get `deprecated.daemonset.template.generation` annotation anyways
=> fix(vector): Allow empty workloadResourceAnnotations

charts/vector/templates/daemonset.yaml, charts/vector/templates/deployment.yaml, charts/vector/templates/statefulset.yaml, charts/vector/values.yaml
Changes to secrets or extra manifests defined does not trigger a rolling restart.
This PR adds an option to do that.
Normally I would turn `.Values.rollWorkload` into an object, then defined something like this 
```yaml
rollWorkload:
configMap: true
secrets: false
extraObjects: false
```
but that would be a breaking change. Maybe something to consider for the next major release of this chart.
=> feat(vector): Add option to roll vector pods on secrets and extra objects change

charts/vector/Chart.yaml, charts/vector/README.md
Missed in https://github.com/vectordotdev/helm-charts/pull/439. I also added these as required checks before merge.
=> chore(vector): Regenerate docs and bump chart version

charts/vector/Chart.yaml, charts/vector/templates/configmap.yaml, charts/vector/templates/daemonset.yaml, charts/vector/templates/deployment.yaml, charts/vector/templates/ingress.yaml, charts/vector/templates/secret.yaml, charts/vector/templates/service-headless.yaml, charts/vector/templates/service.yaml, charts/vector/templates/serviceaccount.yaml, charts/vector/templates/statefulset.yaml
fix 
https://github.com/vectordotdev/helm-charts/pull/394
=> enhancement(vector): Add `namespace` to manifests

charts/vector/Chart.yaml, charts/vector/README.md, charts/vector/templates/ingress.yaml, charts/vector/templates/statefulset.yaml
I've been running into issues deploying newer versions of Vector a custom release tool due to the use of `GitVersion` which is an undocumented Helm behavior described in https://github.com/helm/helm/issues/12072. This changes a few conditionals to just user `Version`
=> fix(vector): Use `.KubeVersion.Version` rather than `.KubeVersion.GitVersion` for capability detection

charts/vector/templates/podmonitor.yaml
This PR fixes an issue where the PodMonitor resource was missing the namespace declaration. Without the namespace being explicitly defined, the PodMonitor resource may be created in the wrong namespace, leading to potential monitoring issues or deployment inconsistencies.
=> fix(vector): Set podmonitor namespace

charts/vector/templates/podmonitor.yaml
This prevents errors when namespaces are "numeric"
=> fix(vector): Quote namespace strings

charts/vector/Chart.yaml, charts/vector/README.md, charts/vector/templates/_pod.tpl, charts/vector/templates/haproxy/deployment.yaml, charts/vector/values.yaml
support tpl in extraContainers and initContainers.
=> feat(vector):  Support tpl for init and extra containers.
